### ISSUE TITLE
ModuleNotFoundError: No module named '_swigfaiss'

### ISSUE THREAD

**Issue by yukaizhou** [yxgeee/SpCL#5]

**Comment by yxgeee** [comment]
Have you installed `faiss`? 
If not, you could install it referring to https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

**Comment by yukaizhou** [comment]
I had run the file setup.py

**Comment by yukaizhou** [comment]
the detial of error :Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/233540/miniconda3/envs/tr_37/lib/python3.7/site-packages/faiss-1.5.3-py3.7-linux-x86_64.egg/faiss/__init__.py", line 19, in <module>
    from .swigfaiss import *
  File "/home/233540/miniconda3/envs/tr_37/lib/python3.7/site-packages/faiss-1.5.3-py3.7-linux-x86_64.egg/faiss/swigfaiss.py", line 17, in <module>
    _swigfaiss = swig_import_helper()
  File "/home/233540/miniconda3/envs/tr_37/lib/python3.7/site-packages/faiss-1.5.3-py3.7-linux-x86_64.egg/faiss/swigfaiss.py", line 16, in swig_import_helper
    return importlib.import_module('_swigfaiss')
  File "/home/233540/miniconda3/envs/tr_37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_swigfaiss'

**Comment by yxgeee** [comment]
There are some issues with the installed `faiss`. Maybe it is caused by losing some dependencies when installing with `pip` (which was done by running setup). Try to install it again with `conda` by
```
conda install faiss-gpu cudatoolkit=8.0 -c pytorch # For CUDA8
conda install faiss-gpu cudatoolkit=9.0 -c pytorch # For CUDA9
conda install faiss-gpu cudatoolkit=10.0 -c pytorch # For CUDA10
```

**Comment by yukaizhou** [comment]
ok thx
